version: 2

sphinx:
  configuration: doc/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"

  apt_packages:
    - default-libmysqlclient-dev
    - build-essential

python:
  install:
    - requirements: doc/requirements.txt

