version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

  apt_packages:
    - default-libmysqlclient-dev
    - build-essential

python:
  install:
    - requirements: doc/requirements.txt

