trigger:
  tags:
    include:
      - '*'
  branches:
    include:
    - master
pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'tiledb/tiledb-sql-py'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: Dockerfile
    tags: |
      $(build.SourceBranchName)

- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: Dockerfile
    tags: |
      latest
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags'))

- task: Docker@2
  displayName: Push image
  inputs:
    containerRegistry: |
      dockerHub
    repository: $(imageName)
    command: push
    tags: |
      $(build.SourceBranchName)
  condition: and(succeeded(), or(eq(variables['Build.SourceBranchName'], 'master'), startsWith(variables['Build.SourceBranch'], 'refs/tags')))

- task: Docker@2
  displayName: Push image
  inputs:
    containerRegistry: |
      dockerHub
    repository: $(imageName)
    command: push
    tags: |
      latest
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags'))
