name: Django compat test

on:
  push:

jobs:
  build:
    name: "Run Django LTS test suite"
    runs-on: ubuntu-latest
    env:
      PIP_NO_PYTHON_VERSION_WARNING: 1
      PIP_DISABLE_PIP_VERSION_CHECK: 1
      DJANGO_VERSION: "3.2.19"
    steps:
      - name: Start MySQL
        run: |
          sudo systemctl start mysql.service
          mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -uroot -proot mysql
          mysql -uroot -proot -e "CREATE USER 'scott'@'%' IDENTIFIED BY 'tiger'; GRANT ALL ON *.* TO scott;"
          mysql -uroot -proot -e "CREATE DATABASE django_default; CREATE DATABASE django_other;"

      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          # Django 3.2.9+ supports Python 3.10
          # https://docs.djangoproject.com/ja/3.2/releases/3.2/
          python-version: "3.10"

      - name: Install mysqlclient
        run: |
          #pip install -r requirements.txt
          pip install mysqlclient  # Use stable version
          pip install .

      - name: Setup Django
        run: |
          sudo apt-get install libmemcached-dev
          wget https://github.com/django/django/archive/${DJANGO_VERSION}.tar.gz
          tar xf ${DJANGO_VERSION}.tar.gz
          cp ci/test_mysql.py django-${DJANGO_VERSION}/tests/
          cd django-${DJANGO_VERSION}
          pip install .  -r requirements/py3.txt

      - name: Run Django test
        run: |
          cd django-${DJANGO_VERSION}/tests/
          PYTHONPATH=.. python3 ./runtests.py --settings=test_mysql
