name: Build windows wheels

on:
  push:
    branches: ["main", "ci"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            cmake_arch: x64
            cibw_arch: AMD64
          - os: windows-11-arm
            cmake_arch: ARM64
            cibw_arch: ARM64
    runs-on: ${{ matrix.os }}
    env:
      CONNECTOR_VERSION: "3.4.8"
    steps:
      - name: Cache Connector
        id: cache-connector
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: c:/mariadb-connector
          key: mariadb-connector-c-${{ env.CONNECTOR_VERSION }}-win-${{ matrix.cmake_arch }}-2

      - name: Download and Unzip Connector
        if: steps.cache-connector.outputs.cache-hit != 'true'
        shell: bash
        run: |
          curl -LO "https://dlm.mariadb.com/4516912/Connectors/c/connector-c-${CONNECTOR_VERSION}/mariadb-connector-c-${CONNECTOR_VERSION}-src.zip"
          unzip "mariadb-connector-c-${CONNECTOR_VERSION}-src.zip" -d c:/
          mv "c:/mariadb-connector-c-${CONNECTOR_VERSION}-src" c:/mariadb-connector-src

      - name: make build directory
        if: steps.cache-connector.outputs.cache-hit != 'true'
        shell: cmd
        working-directory: c:/mariadb-connector-src
        run: |
          mkdir build

      - name: cmake
        if: steps.cache-connector.outputs.cache-hit != 'true'
        shell: cmd
        working-directory: c:/mariadb-connector-src/build
        run: |
          cmake -A ${{ matrix.cmake_arch }} .. -DCMAKE_BUILD_TYPE=Release -DCLIENT_PLUGIN_DIALOG=static -DCLIENT_PLUGIN_SHA256_PASSWORD=static -DCLIENT_PLUGIN_CACHING_SHA2_PASSWORD=static -DDEFAULT_SSL_VERIFY_SERVER_CERT=0

      - name: cmake build
        if: steps.cache-connector.outputs.cache-hit != 'true'
        shell: cmd
        working-directory: c:/mariadb-connector-src/build
        run: |
          cmake --build . -j 8 --config Release

      - name: cmake install
        if: steps.cache-connector.outputs.cache-hit != 'true'
        shell: cmd
        working-directory: c:/mariadb-connector-src/build
        run: |
          cmake -DCMAKE_INSTALL_PREFIX=c:/mariadb-connector -DCMAKE_INSTALL_COMPONENT=Development -DCMAKE_BUILD_TYPE=Release -P cmake_install.cmake

      - name: Checkout mysqlclient
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: mysqlclient

      - name: Site Config
        shell: bash
        working-directory: mysqlclient
        run: |
          pwd
          find .
          cat <<EOF >site.cfg
          [options]
          static = True
          connector = C:/mariadb-connector
          EOF
          cat site.cfg

      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel
      - name: Build wheels
        working-directory: mysqlclient
        env:
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.10"
          CIBW_ARCHS: ${{ matrix.cibw_arch }}
          CIBW_TEST_COMMAND: 'python -c "import MySQLdb; print(MySQLdb.version_info)" '
        run: "python -m cibuildwheel --output-dir dist"

      - name: Build sdist
        if: matrix.cibw_arch == 'AMD64'
        working-directory: mysqlclient
        run: |
          python -m pip install build
          python -m build -s -o dist

      - name: Upload Wheel
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: win-wheels-${{ matrix.cibw_arch }}
          path: mysqlclient/dist/*.*
